### PR TITLE
[WIP] Add new proxy providers

### PR DESCRIPTION
**Pull request by ydakuka**

### CODE REVIEW

**Comment by nbulaj** [comment]
Love this :heart:

**Comment by ydakuka** [comment]
Oh sorry, I still want to finish this. There is not enough time for the last month.

**Comment by JuPlutonic** [comment]
Need this PR to be merged quicker, because now only working provider is force_proxy_list_ssl
```ruby
my ISP: "МТС",
test from console (-p each_provider >> proxies.txt)
{ expired: %i[free_proxy_list free_proxy_list_us free_proxy_list_socks proxyscrape_http proxypedia],
  0: %i[free_proxy_list http_tunnel mtpro proxy_list proxyscrape_socks4 proxyscrape_socks5 xroxy] }
```

@ydakuka, please megre (ruby3 related) last main changes to your PR.

**Comment by JuPlutonic** [comment]
FYI results of checking changed providers (new/xpath/naming/pagination)
```
~checker_proxy~
W, [2022-08-12T14:35:48.087251 #14347]  WARN -- : Failed to process request to https://checkerproxy.net/api/archive/2022-08-12 (error reading from socket: Could not parse data)
~f_p_cz~
//208.52.137.X:P
//208.52.137.X:P
//208.52.137.X:P
//208.52.180.X:P
~f_p_l~
0 – nothing
~f_p_l_socks~
W, [2022-08-12T14:39:33.114649 #24986]  WARN -- : Failed to process request to https://www.socks-proxy.net/ (error reading from socket: Could not parse data)
~f_p_l_us~
0 – nothing
~proxy_list~
//8.210.155.X:P
//103.252.1.X:P
~proxy_list_download_http~
0 – nothing
~proxy_list_download_https~
0 – nothing
~proxy_list_download_socks4~
0 – nothing
~proxy_list_download_socks5~
0 – nothing
~proxyscrape_http~
//85.14.243.X:P
//89.208.219.X:P
//121.156.109.X:P
//103.252.1.X:P
//81.23.100.X:P
~proxyscrape_socks4~
0 – nothing
```
proxyscrape_socks4, scapingant and xroxy I will test later.

**Comment by ydakuka** [comment]
@JuPlutonic I don't work with it anymore. Feel free to complete MR.

**Comment by JuPlutonic** [comment]
Ok, the PR/MR will be tested after the 0.16.0/main rebase on it and after recheck. App with the ProxyFetcher::Client will be run and logged with providers mentioned above with ISPs: МТС/another.

**Pull request closed without merging**
